version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: example
      POSTGRES_DB: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    image: odoo:14
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: example
    volumes:
      - odoo-data:/var/lib/odoo
    networks:
      - odoo-network

volumes:
  db-data:
  odoo-data:

networks:
  odoo-network:
