version: '3.1'

services:
  web:
    image: odoo:17.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - odoo-data:/var/lib/odoo
    networks:
      - odoo-network

  mydb:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo

    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

volumes:
  db-data:
  odoo-data:

networks:
  odoo-network:
