apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: odoo:latest
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: "postgres-service"
            - name: PORT
              value: "5432"
            - name: USER
              value: "odoo" # for public deployment change this to secrets "user"
            - name: PASSWORD
              value: "example" # odoo" "for public deployment change this to secrets "user"
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: odoo-storage
      volumes:
        - name: odoo-storage
          persistentVolumeClaim:
            claimName: odoo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 8069
