apiVersion: v1
kind: Secret
metadata:
  name: odoo-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: "b2Rvb191c2VyCg==" # base64 encoded user (example: 'odoo_user')
  POSTGRES_PASSWORD: "b2Rvb19wYXNzd29yZAo=" # base64 encoded password (example: 'odoo_password')
  ODOO_ADMIN_PASSWORD: "YWRtaW4=" # base64 encoded admin password (example: 'admin')
